language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script:
  - jdk_switcher use $TRAVIS_JDK_VERSION
  - mvn test -Dmaven.javadoc.skip=true
